### PR TITLE
Match va_start and va_end calls, pointed by clang-tidy

### PR DESCRIPTION
**Pull request by bvbfan**
Signed-off-by: Anthony Fieroni <bvbfan@abv.bg>

### CODE REVIEW

**Comment by BrannonKing** [comment]
Do you know if this is fixed in the upstream bitcoin codebase?

**Comment by bvbfan** [comment]
Yes, it is.

**Comment by bvbfan** [comment]
@BrannonKing you can close this RR.

**Comment by bvbfan** [comment]
It'll be fixes as master bitcoin merge

**Pull request closed without merging**
