### PR TITLE
Re-enable dust threshold checks

### PR DESCRIPTION
**Pull request by kaykurokawa**
for https://github.com/lbryio/lbrycrd/issues/25

undos https://github.com/lbryio/lbrycrd/commit/a6984a9d72f9231ff850050b0193342a1ce8c043

### CODE REVIEW

**Comment by kaykurokawa** [comment]
lowering dust threshold to 1, to not break lbrynet and still have some spam protection

**Comment by jimmykiselak** [comment]
This should not be merged until lbrynet has been modified so that it will never try to create a txout with a value of 0.

**Comment by jimmykiselak** [comment]
https://github.com/lbryio/lbry/ related issue: https://github.com/lbryio/lbry/issues/138

**Comment by jobevers** [comment]
These changes LGTM; merging.

**Pull request merged**
