### PR TITLE
keep the block filter entirely in sqlite

### LINKED ISSUE #383: No block filters after restart
**Expected behavior**

Sync or reindex, get block filters, restart, get block filters...

**Actual behavior**

Sync or reindex, get block filters, restart, error:
```
./lbrycrd-cli getblockfilter $(./lbrycrd-cli getblockhash 2)
error code: -32603
error message:
Filter not found. This error is unexpected and indicates index corruption.
```
this also gets logged:
`2020-04-07T19:49:54Z ERROR: ReadFilterFromDisk: Failed to deserialize block filter from disk: VectorReader::read(): end of data: iostream error`

**To reproduce**
Using that line on config: `blockfilterindex=1`
Restart during or after sync.

### PR DESCRIPTION
**Pull request by BrannonKing**
and made it work right.

Fixes #383

### CODE REVIEW

**Comment by bvbfan** [comment]
We can unite filter and filter header as well? Do we need separate functions?

**Comment by BrannonKing** [comment]
Yes, the code is repetitive. Feel free to make a convenient way to pass the column name (and return type) and reuse the code.

**Comment by BrannonKing** [comment]
Did I mention how pleased I was with the amount of code that I deleted?

**Comment by bvbfan** [comment]
What was the problem in #383 i can't reproduce it?

**Comment by BrannonKing** [comment]
#383 was a corrupt flat file. I'm not sure how he got one. I'm declaring it fixed by not using the flat file any more.

**Comment by bvbfan** [comment]
OK, +1 from me, i've test the changes, running test as well.

**Pull request merged**
