### PR TITLE
Updates to allow successful build on OpenSSL 1.1+

### PR DESCRIPTION
**Pull request by DivineLinx**
Updating;

-- paymentrequestplus.cpp
-- crypter.cpp

To allow successful build on new releases of Debian (stretch), Ubuntu (18+), Fedora wherein OpenSSL is version 1.1

Following the update lbrycrdd builds successfully.

### CODE REVIEW

**Comment by BrannonKing** [comment]
FYI, this is also fixed upstream (and would be repaired by #174 ).

**Comment by DivineLinx** [comment]
@BrannonKing Thanks :+1:

**Comment by lbrynaut** [comment]
Marked as on-hold pending upstream merge.  If needed can revisit then, but as indicated, it should no longer be necessary at that point.

**Comment by BrannonKing** [comment]
closing in favor of #221

**Comment by BrannonKing** [comment]
This is now merged/fixed.

**Pull request closed without merging**
