### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amaljose02**
Added Table of contents, PR welcome and License badges

### CODE REVIEW

**Comment by BrannonKing** [comment]
Why `h2` instead of `##`?

**Comment by amaljose02** [comment]
I aligned the headings to center using h2 tags first, then i changed the alignment to left, so i used h2 tags instead of ##.

**Comment by tzarebczan** [comment]
@amaljose02 can you fix the last h2 on contributing? 

Thanks for the PR! 

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution? 

Also, we're giving away some [Hacktoberfest](https://lbry.com/news/hacktoberfest-2019) bonuses and goodies for this month. We'll get it all figured out after you shoot us an email after this is reviewed/merged.

**Comment by amaljose02** [comment]
@tzarebczan sorry, i didn't noticed the `h2` at contribution. I've now changed the `h2` to `##`.

**Comment by BrannonKing** [comment]
Please rebase and squash this.

**Comment by BrannonKing** [comment]
closing in favor of #339

**Pull request closed without merging**
